# Generated by Django 2.2.5 on 2019-10-16 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('n_max', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'evento',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Eventos.Evento')),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=100)),
                ('cp', models.CharField(max_length=100)),
                ('edo', models.CharField(max_length=100)),
                ('colonia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Etiquetas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=100)),
                ('evento', models.ManyToManyField(to='Eventos.Evento')),
            ],
            options={
                'db_table': 'etiquetas',
            },
        ),
    ]
